name: Test
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - package.json
      - 'examples/*/**/src/**'
      - 'packages/*/**/src/**'
      - 'packages/*/**/package.json'
      - .github/workflows/test.yml

env:
  BUILD_PATH: "" # default value when not using subfolders

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Nodes
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build package
        run: ${{ steps.detect-package-manager.outputs.manager }} run build:package
      
      - name: Build page
        run: ${{ steps.detect-package-manager.outputs.manager }} run build --workspace=browser

      - name: Run generate
        run: ${{ steps.detect-package-manager.outputs.manager }} run test:examples

      - name: Check images
        run: |
          du -sh ${{ github.workspace }}/examples/node/dist/basic.png
          du -sh ${{ github.workspace }}/examples/ts-node/dist/basic.png
